### ISSUE TITLE
Homework4 from AlexShk

### ISSUE THREAD

**Issue by alexshk76** [WEB-road/Shkarbuta_Homework4#1]
Please review my work and make comments.

**Comment by Appof** [comment]
- Це не форма, а скоріше посилання на місце/сторінку з коментарями 
https://github.com/WEB-road/Shkarbuta_Homework4/blob/cc93dc0fb3c981e91d9ead4aa0798ebc5f5721ff/index.html#L32-L34
- Хитро, але можна легко розмістити всі чотири карточки, нерозділяючи їх дівами. Використовуйте флексбокси.
https://github.com/WEB-road/Shkarbuta_Homework4/blob/cc93dc0fb3c981e91d9ead4aa0798ebc5f5721ff/index.html#L36
https://github.com/WEB-road/Shkarbuta_Homework4/blob/cc93dc0fb3c981e91d9ead4aa0798ebc5f5721ff/index.html#L54
- Тут мейн не закінчується, форма і дві нижні картки теж відносяться до головного контенту. 
https://github.com/WEB-road/Shkarbuta_Homework4/blob/cc93dc0fb3c981e91d9ead4aa0798ebc5f5721ff/index.html#L72
- Іконки та посилання краще робити одного кольору зі шрифтом(сірим). Це буде виглядати привабливіше.https://github.com/WEB-road/Shkarbuta_Homework4/blob/cc93dc0fb3c981e91d9ead4aa0798ebc5f5721ff/index.html#L109-L119
- Також для підвищення сприйняття юзером інформації посиланням дають ховер ефект. Можна просто змінити колір на темніший при наведенні мишки.

**Comment by alexshk76** [comment]
Пофіксив, як Ви зауважили.

**Comment by Appof** [comment]
- Властивість переходу достатньо вказати раз до елементу що буде використовувати цю анімацію. https://github.com/WEB-road/Shkarbuta_Homework4/blob/8494cf52e77d767a4d5a198e1a85069a39ed993c/css/style.css#L57-L58
- Доцільніше використовувати властивість transform, якщо є потреба збільшити елемент. https://github.com/WEB-road/Shkarbuta_Homework4/blob/8494cf52e77d767a4d5a198e1a85069a39ed993c/css/style.css#L59
- row завжди по замовчуванню застосовується(прибрати повсюди) https://github.com/WEB-road/Shkarbuta_Homework4/blob/8494cf52e77d767a4d5a198e1a85069a39ed993c/css/style.css#L64
- позиціонування тут не потрбіно https://github.com/WEB-road/Shkarbuta_Homework4/blob/8494cf52e77d767a4d5a198e1a85069a39ed993c/css/style.css#L66
- Дві різні назви, а властивості одні, можна зробити одним спільним класом https://github.com/WEB-road/Shkarbuta_Homework4/blob/8494cf52e77d767a4d5a198e1a85069a39ed993c/css/style.css#L95 https://github.com/WEB-road/Shkarbuta_Homework4/blob/8494cf52e77d767a4d5a198e1a85069a39ed993c/css/style.css#L103
- Контейнер і так 900 пкс, тут ширина не потрібна https://github.com/WEB-road/Shkarbuta_Homework4/blob/8494cf52e77d767a4d5a198e1a85069a39ed993c/css/style.css#L97
- Просто дів? https://github.com/WEB-road/Shkarbuta_Homework4/blob/8494cf52e77d767a4d5a198e1a85069a39ed993c/index.html#L29
- знак https://github.com/WEB-road/Shkarbuta_Homework4/blob/8494cf52e77d767a4d5a198e1a85069a39ed993c/css/style.css#L140

**Comment by Appof** [comment]
Закоментований код краще не залишати. 
https://github.com/WEB-road/Shkarbuta_Homework4/blob/02eda2c15b2efce24955709590c5a0a763e57044/css/style.css#L55-L62
duration також вказується до головного елементу, а не псевдокласу

**Comment by alexshk76** [comment]
Пофіксив, ніби-то все. Чекаю на коменти.
